# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4092da1d7da5517c3278842776594c095b0b69e8af89b4992d4a7281e32b871b52bbcbd6b48a436717cf926621a47a796bb6f8be1b7fa13cec375167501011ad

test:
  secret_key_base: 96ed0272bc8a2cdaae30963927da56c0674d1b8eb9f76672990df9cd6fb5987b476fa6ef725897fe06dd81cad3790a01af8a0fa9812a70d223e092204dfc8465

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
